---
name: javascript-checks

"on":
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  execute-command:
    name: execute-command-${{ matrix.command }}
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        command: [build, check-format, eslint, typecheck]

    steps:
      - uses: actions/checkout@v7

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'
      - run: npm install -g yarn

      - name: Install Foundry
        run: |
          # first install it
          unset XDG_CONFIG_HOME
          curl -L https://foundry.paradigm.xyz | bash
          ~/.foundry/bin/foundryup

          echo "$HOME/.foundry/bin" >> "$GITHUB_PATH"

      - name: Install forge-std
        run: git clone --depth 1 https://github.com/foundry-rs/forge-std lib/forge-std

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Execute command ${{ matrix.command }}
        run: |
          yarn ${{ matrix.command }}
